// Copyright (c) 2026 Sebastian Toivonen
// SPDX-License-Identifier: Apache-2.0

internal import CNVRTC

private final class NVRTCFlowCallbackBox: @unchecked Sendable {
    let shouldCancel: @Sendable () -> Bool

    init(_ shouldCancel: @escaping @Sendable () -> Bool) {
        self.shouldCancel = shouldCancel
    }
}

private func nvrtcFlowCallback(
    _ payload: UnsafeMutableRawPointer?,
    _ reserved: UnsafeMutableRawPointer?
) -> Int32 {
    guard let payload else { return 0 }
    let box = Unmanaged<NVRTCFlowCallbackBox>
        .fromOpaque(payload)
        .takeUnretainedValue()
    return box.shouldCancel() ? 1 : 0
}

extension NVRTC {
    /// A reference-counted owner of an `nvrtcProgram`.
    ///
    /// The program can be compiled repeatedly with different options. Output,
    /// logs, and lowered names always refer to the most recent compilation.
    public final class Program {
        private var rawValue: SebbuNVRTCProgram?
        private var flowCallbackBox: NVRTCFlowCallbackBox?

        public init(
            source: String,
            name: String? = nil,
            headers: [Header] = []
        ) throws {
            try nvrtcValidateCString(source, field: "source")
            let headerCount = try nvrtcInt32Count(
                headers.count,
                field: "header count"
            )
            let headerSources = headers.map(\.source)
            let includeNames = headers.map(\.includeName)

            var program: SebbuNVRTCProgram?
            let result = try source.withCString { sourcePointer in
                try nvrtcWithOptionalCString(name, field: "program name") {
                    namePointer in
                    try nvrtcWithCStringArray(
                        headerSources,
                        field: "header source"
                    ) { headerPointers in
                        try nvrtcWithCStringArray(
                            includeNames,
                            field: "header include name"
                        ) { includeNamePointers in
                            sebbuNvrtcCreateProgram(
                                &program,
                                sourcePointer,
                                namePointer,
                                headerCount,
                                headerPointers,
                                includeNamePointers
                            )
                        }
                    }
                }
            }
            try nvrtcCheck(result)
            guard let program else {
                throw NVRTC.Error(
                    NVRTC.Error.Code.programCreationFailure.rawValue,
                    detailedMessage: "NVRTC returned success without a program handle."
                )
            }
            rawValue = program
        }

        deinit {
            if rawValue != nil {
                var program = rawValue
                _ = sebbuNvrtcDestroyProgram(&program)
                rawValue = nil
            }
        }

        /// Compiles using typed command-line options.
        public func compile(options: [CompileOption] = []) throws {
            let arguments = options.map(\.commandLineArgument)
            let count = try nvrtcInt32Count(
                arguments.count,
                field: "compile-option count"
            )
            let result = try nvrtcWithCStringArray(
                arguments,
                field: "compile option"
            ) { pointers in
                sebbuNvrtcCompileProgram(rawValue, count, pointers)
            }
            guard result != 0 else { return }
            if result == -1 {
                try nvrtcCheck(result, feature: "program compilation")
            }
            let compilationLog = (try? log()) ?? ""
            throw CompilationError(
                error: Error(result),
                log: compilationLog
            )
        }

        /// Compiles using the common structured option model.
        public func compile(options: CompileOptions) throws {
            try compile(options: options.compileOptions)
        }

        /// The PTX text generated by the most recent compilation.
        public func ptx() throws -> String {
            try nvrtcReadString(
                size: { sebbuNvrtcGetPTXSize(rawValue, $0) },
                read: { sebbuNvrtcGetPTX(rawValue, $0) }
            )
        }

        /// The native cubin generated for a real `sm_XX` architecture.
        public func cubin() throws -> [UInt8] {
            try nvrtcReadBytes(
                feature: "cubin output",
                size: { sebbuNvrtcGetCUBINSize(rawValue, $0) },
                read: { sebbuNvrtcGetCUBIN(rawValue, $0) }
            )
        }

        /// LTO IR generated when device link-time optimization was requested.
        public func ltoIR() throws -> [UInt8] {
            try nvrtcReadBytes(
                feature: "LTO IR output",
                size: { sebbuNvrtcGetLTOIRSize(rawValue, $0) },
                read: { sebbuNvrtcGetLTOIR(rawValue, $0) }
            )
        }

        /// OptiX IR generated when the `optiXIR` option was requested.
        public func optiXIR() throws -> [UInt8] {
            try nvrtcReadBytes(
                feature: "OptiX IR output",
                size: { sebbuNvrtcGetOptiXIRSize(rawValue, $0) },
                read: { sebbuNvrtcGetOptiXIR(rawValue, $0) }
            )
        }

        /// CUDA Tile IR generated for Tile code by CUDA 13.3 and later.
        public func tileIR() throws -> [UInt8] {
            try nvrtcReadBytes(
                feature: "CUDA Tile IR output",
                size: { sebbuNvrtcGetTileIRSize(rawValue, $0) },
                read: { sebbuNvrtcGetTileIR(rawValue, $0) }
            )
        }

        /// The diagnostic log from the most recent compilation.
        public func log() throws -> String {
            try nvrtcReadString(
                size: { sebbuNvrtcGetProgramLogSize(rawValue, $0) },
                read: { sebbuNvrtcGetProgramLog(rawValue, $0) }
            )
        }

        /// Registers a function or variable expression for name lowering.
        /// Call this before compilation.
        public func addNameExpression(_ expression: String) throws {
            try nvrtcValidateCString(expression, field: "name expression")
            try expression.withCString {
                try nvrtcCheck(
                    sebbuNvrtcAddNameExpression(rawValue, $0)
                )
            }
        }

        /// Returns the lowered name of a previously registered expression.
        /// Call this after a successful compilation.
        public func loweredName(for expression: String) throws -> String {
            try nvrtcValidateCString(expression, field: "name expression")
            var loweredName: UnsafePointer<CChar>?
            try expression.withCString {
                try nvrtcCheck(
                    sebbuNvrtcGetLoweredName(rawValue, $0, &loweredName)
                )
            }
            guard let loweredName else {
                throw NVRTC.Error(
                    NVRTC.Error.Code.internalError.rawValue,
                    detailedMessage: "NVRTC returned success without a lowered name."
                )
            }
            return String(cString: loweredName)
        }

        /// Installs a compilation-cancellation callback.
        ///
        /// The callback must be thread-safe and must keep returning `true`
        /// after it first requests cancellation. It must not invoke NVRTC,
        /// libNVVM, or PTX APIs.
        public func setCancellationHandler(
            _ shouldCancel: @escaping @Sendable () -> Bool
        ) throws {
            let box = NVRTCFlowCallbackBox(shouldCancel)
            try nvrtcCheck(
                sebbuNvrtcSetFlowCallback(
                    rawValue,
                    nvrtcFlowCallback,
                    Unmanaged.passUnretained(box).toOpaque()
                ),
                feature: "compilation cancellation callbacks"
            )
            flowCallbackBox = box
        }

        /// Status of PCH creation during the most recent compilation.
        public func pchCreationStatus() throws -> PCHCreationStatus {
            let result = sebbuNvrtcGetPCHCreateStatus(rawValue)
            switch result {
            case Error.Code.success.rawValue:
                return .created
            case Error.Code.noPCHCreationAttempted.rawValue:
                return .notAttempted
            case Error.Code.pchCreateHeapExhausted.rawValue:
                return .heapExhausted
            case Error.Code.pchCreate.rawValue:
                return .failed
            default:
                try nvrtcCheck(
                    result,
                    feature: "precompiled-header support"
                )
                fatalError("nvrtcCheck returned for an error result")
            }
        }

        /// Required PCH heap size reported for the most recent compilation.
        public func requiredPCHHeapSize() throws -> Int {
            var size = 0
            try nvrtcCheck(
                sebbuNvrtcGetPCHHeapSizeRequired(rawValue, &size),
                feature: "precompiled-header support"
            )
            return size
        }
    }
}
